FROM ubuntu
# Install all dependencies.
RUN echo 'y' | apt-get update && \
    echo 'y' | apt-get install software-properties-common
RUN \
  echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
  add-apt-repository -y ppa:webupd8team/java && \
  apt-get update && \
  apt-get install -y oracle-java8-installer && \
  rm -rf /var/lib/apt/lists/* && \
  rm -rf /var/cache/oracle-jdk8-installer

ENV JAVA_HOME /usr/lib/jvm/java-8-oracle
COPY Manager.jar /usr/src/app/
WORKDIR /data
EXPOSE 8090

# run the application
CMD ["java","-jar","/usr/src/app/Manager.jar"]
